

echo ; 

export JWT_ISSUER="XXXXXXXXXXXXXXXXXXXXX"
export ROOT_ACCOUNT="XXXXXXXXXXXXXXXXXXXXX"
export TOKEN_SECRET_KEY="XXXXXXXXXXXXXXXXXXXXX"
export TOKEN_ROOT_SECRET_KEY="XXXXXXXXXXXXXXXXXXXXX"
export DATABASE_URL="XXXXXXXXXXXXXXXXXXXXX"
export SPACES_KEY="XXXXXXXXXXXXXXXXXXXXX"
export SPACES_SECRET="XXXXXXXXXXXXXXXXXXXXX"
export SPACES_NAME="XXXXXXXXXXXXXXXXXXXXX"
export SPACES_ENDPOINT="XXXXXXXXXXXXXXXXXXXXX"
export VALID_API_URL="XXXXXXXXXXXXXXXXXXXXX"
export TICKET_SECRET_KEY="XXXXXXXXXXXXXXXXXXXXX"
export RATE_SECRET_KEY="XXXXXXXXXXXXXXXXXXXXX"
export X_API_KEY="XXXXXXXXXXXXXXXXXXXXX"
export COOKIE_ALLOWED_DOMAINS="XXXXXXXXXXXXXXXXXXXXX"
export IS_HTTP_ONLY_AUTH_COOKIE="XXXXXXXXXXXXXXXXXXXXX"
export IS_HTTP_SSL="XXXXXXXXXXXXXXXXXXXXX"

echo done