# Copyright (c) 2017-2026 Onur Yaşar
# Licensed under AGPL v3 + Commercial Exception
# See LICENSE.txt

# https://github.com/rymory/rymory-core
# rymory.org 
# onuryasar.org
# onxorg@proton.me 

packages:
  - name: security
    environment:
        JWT_ISSUER: ${JWT_ISSUER}
        ROOT_ACCOUNT: ${ROOT_ACCOUNT}
        TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
        TOKEN_ROOT_SECRET_KEY: ${TOKEN_ROOT_SECRET_KEY}
        DATABASE_URL: ${DATABASE_URL}
        SPACES_KEY: ${SPACES_KEY}
        SPACES_SECRET: ${SPACES_SECRET}
        SPACES_NAME: ${SPACES_NAME}
        SPACES_ENDPOINT: ${SPACES_ENDPOINT}
        VALID_API_URL: ${VALID_API_URL}
        TICKET_SECRET_KEY: ${TICKET_SECRET_KEY}
        RATE_SECRET_KEY: ${RATE_SECRET_KEY}
        X_API_KEY: ${X_API_KEY}
        COOKIE_ALLOWED_DOMAINS: ${COOKIE_ALLOWED_DOMAINS}
    functions:
      - name: authenticate
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
      - name: account
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
      - name: role
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
      - name: validation
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
      - name: ticket
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
    
  - name: system
    environment:
        JWT_ISSUER : ${JWT_ISSUER}
        ROOT_ACCOUNT : ${ROOT_ACCOUNT}
        TOKEN_SECRET_KEY : ${TOKEN_SECRET_KEY}
        TOKEN_ROOT_SECRET_KEY : ${TOKEN_ROOT_SECRET_KEY}
        DATABASE_URL: ${DATABASE_URL}
        SPACES_KEY: ${SPACES_KEY}
        SPACES_SECRET: ${SPACES_SECRET}
        SPACES_ENDPOINT: ${SPACES_ENDPOINT}
        SPACES_NAME: ${SPACES_NAME}
        VALID_API_URL: ${VALID_API_URL}
    functions:
      - name: file
        runtime: nodejs:14
        # web: true  
        limits:
          timeout: 3000
          memory: 512
      - name: init
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
      - name: zombie
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
      - name: project
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
      - name: member
        runtime: go:1.20
        # web: true  
        limits:
          timeout: 3000
          memory: 128
      - name: space
        runtime: nodejs:14
        # web: true  
        limits:
          timeout: 3000
          memory: 512